// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package testprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TestTestServiceClient is the client API for TestTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestTestServiceClient interface {
	UserAuth(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error)
	Get(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error)
}

type testTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestTestServiceClient(cc grpc.ClientConnInterface) TestTestServiceClient {
	return &testTestServiceClient{cc}
}

func (c *testTestServiceClient) UserAuth(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/foo.bar.TestTestService/UserAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testTestServiceClient) Get(ctx context.Context, in *Test, opts ...grpc.CallOption) (*Test, error) {
	out := new(Test)
	err := c.cc.Invoke(ctx, "/foo.bar.TestTestService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestTestServiceServer is the server API for TestTestService service.
type TestTestServiceServer interface {
	UserAuth(context.Context, *Test) (*Test, error)
	Get(context.Context, *Test) (*Test, error)
}

// UnimplementedTestTestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTestTestServiceServer struct {
}

func (*UnimplementedTestTestServiceServer) UserAuth(context.Context, *Test) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAuth not implemented")
}
func (*UnimplementedTestTestServiceServer) Get(context.Context, *Test) (*Test, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterTestTestServiceServer(s *grpc.Server, srv TestTestServiceServer) {
	s.RegisterService(&_TestTestService_serviceDesc, srv)
}

func _TestTestService_UserAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestTestServiceServer).UserAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foo.bar.TestTestService/UserAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestTestServiceServer).UserAuth(ctx, req.(*Test))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestTestService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestTestServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foo.bar.TestTestService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestTestServiceServer).Get(ctx, req.(*Test))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestTestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "foo.bar.TestTestService",
	HandlerType: (*TestTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserAuth",
			Handler:    _TestTestService_UserAuth_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TestTestService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desc_test_complex.proto",
}
